
// GET
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

// WSS
export const CHAT_MESSAGE = 'CHAT_MESSAGE'
export const CONNECT = 'CONNECT'
export const DISCONNECT = 'DISCONNECT'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const CONNECTING = 'CONNECTING'
